"""got new userprofile table

Revision ID: 579b7f15ccab
Revises: 851a52eac24a
Create Date: 2025-03-02 15:02:15.906290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579b7f15ccab'
down_revision: Union[str, None] = '851a52eac24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ...existing code...
def upgrade():
    op.create_table(
        'user_profiles',
        sa.Column('clerk_user_id', sa.String(), primary_key=True),
        sa.Column('background', sa.JSON()),
        sa.Column('is_subscribed', sa.Boolean(), server_default='false'),
        sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('NOW()')),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
